<a href="https://colab.research.google.com/github/adityapanwar94/Data-Analysis-and-Process-Automation-DaPrA-/blob/harshini/Dataset_filtering_pc_specs_initial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importing Dataset**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!unzip -q /content/drive/MyDrive/dataset.zip

## **Importing Libraries**

In [3]:
import pandas as pd
import numpy as np

In [4]:
pc_details = pd.read_csv(r'/content/dataset/pc_specs.csv')

In [5]:
pc_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5684 entries, 0 to 5683
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   team_id            5684 non-null   int64
 1   name               5684 non-null   object
 2   machine_name       5684 non-null   object
 3   Single core score  5684 non-null   object
 4   Multi core score   5684 non-null   object
 5   OpenCL score       3934 non-null   object
 6   OS                 5684 non-null   object
 7   Model              5684 non-null   object
 8   CPU                5684 non-null   object
 9   Memory             5684 non-null   object
 10  Graphic Card       3934 non-null   object
 11  comments           1366 non-null   object
 12  observations       1750 non-null   object
dtypes: int64(1), object(12)
memory usage: 577.4+ KB

In [6]:
pc_details.head()

,team_id,name,machine_name,Single core score,Multi core score,OpenCL score,OS,Model,CPU,Memory,Graphic Card,comments,observations
0,1001,Kruthik B S,Dell Inc. Inspiron 3593,1142,2148,NaN,Ubuntu 18.04.5 LTS,Dell Inc. Inspiron 3593,Intel Core i3-1005G1,3.62 GB,NaN,NaN,Same link in both fields
1,1001,Nikhil S,HP HP Laptop 15q-bu0xx,543,1132,3167,Ubuntu 20.04.3 LTS,HP HP Laptop 15q-bu0xx,Intel Core i3-6006U,3.64 GB,Intel(R) HD Graphics 520 (SKL GT2),NaN,NaN
2,1001,Sumanth K S,HP HP Laptop 14q-bu0xx,836,1525,3002,Ubuntu 20.04.3 LTS,HP HP Laptop 14q-bu0xx,Intel Core i5-7200U,3.73 GB,Intel(R) HD Graphics 620 (KBL GT2),NaN,NaN
3,1001,Gagan k,LENOVO 82C7,601,2281,2946,Ubuntu 20.04.3 LTS,LENOVO 82C7,AMD Ryzen 5 3500U,5.74 GB,AMD RADV RAVEN (ACO),NaN,NaN
4,1002,Abhishek Jain,Dell Inc. G3 3590,1060,3394,5735,Microsoft Windows 10 Home Single Language (64-...,Dell Inc. G3 3590,Intel Core i7-9750H,2,3.14 GB,NaN,NaN

## **Removing Teams with less than 2 members**

In [7]:
pc_details['freq'] = pc_details.groupby('team_id')['team_id'].transform('count')
pc_details.count()

team_id              5684
name                 5684
machine_name         5684
Single core score    5684
Multi core score     5684
OpenCL score         3934
OS                   5684
Model                5684
CPU                  5684
Memory               5684
Graphic Card         3934
comments             1366
observations         1750
freq                 5684
dtype: int64

In [8]:
pc_details = pc_details[pc_details.freq >1]
pc_details.count()

team_id              5684
name                 5684
machine_name         5684
Single core score    5684
Multi core score     5684
OpenCL score         3934
OS                   5684
Model                5684
CPU                  5684
Memory               5684
Graphic Card         3934
comments             1366
observations         1750
freq                 5684
dtype: int64

## **Analysing Null and Unique Values in every column**

In [9]:
print(pc_details.isna().sum().sort_values(ascending=False).to_markdown())

|                   |    0 |
|:------------------|-----:|
| comments          | 4318 |
| observations      | 3934 |
| OpenCL score      | 1750 |
| Graphic Card      | 1750 |
| team_id           |    0 |
| name              |    0 |
| machine_name      |    0 |
| Single core score |    0 |
| Multi core score  |    0 |
| OS                |    0 |
| Model             |    0 |
| CPU               |    0 |
| Memory            |    0 |
| freq              |    0 |

In [10]:
pc_details = pc_details.drop(['name'], axis =1)

In [11]:
pc_details

,team_id,machine_name,Single core score,Multi core score,OpenCL score,OS,Model,CPU,Memory,Graphic Card,comments,observations,freq
0,1001,Dell Inc. Inspiron 3593,1142,2148,NaN,Ubuntu 18.04.5 LTS,Dell Inc. Inspiron 3593,Intel Core i3-1005G1,3.62 GB,NaN,NaN,Same link in both fields,4
1,1001,HP HP Laptop 15q-bu0xx,543,1132,3167,Ubuntu 20.04.3 LTS,HP HP Laptop 15q-bu0xx,Intel Core i3-6006U,3.64 GB,Intel(R) HD Graphics 520 (SKL GT2),NaN,NaN,4
2,1001,HP HP Laptop 14q-bu0xx,836,1525,3002,Ubuntu 20.04.3 LTS,HP HP Laptop 14q-bu0xx,Intel Core i5-7200U,3.73 GB,Intel(R) HD Graphics 620 (KBL GT2),NaN,NaN,4
3,1001,LENOVO 82C7,601,2281,2946,Ubuntu 20.04.3 LTS,LENOVO 82C7,AMD Ryzen 5 3500U,5.74 GB,AMD RADV RAVEN (ACO),NaN,NaN,4
4,1002,Dell Inc. G3 3590,1060,3394,5735,Microsoft Windows 10 Home Single Language (64-...,Dell Inc. G3 3590,Intel Core i7-9750H,2,3.14 GB,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5679,2970,Nil,Nil,Nil,NaN,Nil,Nil,Nil,Nil,NaN,CPU URL not valid.Compute URL not valid.,Same link in both fields,4
5680,2971,Nil,Nil,Nil,NaN,Nil,Nil,Nil,Nil,NaN,CPU URL not valid.Compute URL not valid.,Same link in both fields,4
5681,2971,Nil,Nil,Nil,NaN,Nil,Nil,Nil,Nil,NaN,CPU URL not valid.Compute URL not valid.,Same link in both fields,4
5682,2971,Nil,Nil,Nil,NaN,Nil,Nil,Nil,Nil,NaN,CPU URL not valid.Compute URL not valid.,Same link in both fields,4
5683,2971,Nil,Nil,Nil,NaN,Nil,Nil,Nil,Nil,NaN,CPU URL not valid.Compute URL not valid.,Same link in both fields,4

In [12]:
pc_details.columns

Index(['team_id', 'machine_name', 'Single core score', 'Multi core score',
       'OpenCL score', 'OS', 'Model', 'CPU', 'Memory', 'Graphic Card',
       'comments', 'observations', 'freq'],
      dtype='object')

## **Function to create a dateframe indicating count of unique values**

In [13]:
def unique_chart(Dataset):
  uni_dict = {}
  uni_value ={}
  keys = Dataset.columns
  for i in keys:
    uni_dict[i] = Dataset[i].nunique()
    if Dataset[i].nunique() <= 10:
      uni_value[i] = Dataset[i].unique()
    else:
      uni_value[i] = None
  return (uni_dict, uni_value)

In [14]:
uni_dict, uni_value = unique_chart(pc_details)
Unique = pd.DataFrame([uni_dict, uni_value]) 
print(Unique.to_markdown())

|    |   team_id |   machine_name |   Single core score |   Multi core score |   OpenCL score |   OS |   Model |   CPU |   Memory |   Graphic Card | comments                                                                         | observations                     | freq    |
|---:|----------:|---------------:|--------------------:|-------------------:|---------------:|-----:|--------:|------:|---------:|---------------:|:---------------------------------------------------------------------------------|:---------------------------------|:--------|
|  0 |      1481 |           1035 |                1154 |               2739 |           3441 |  101 |    1006 |   412 |      134 |            190 | 6                                                                                | 1                                | 3       |
|  1 |       nan |            nan |                 nan |                nan |            nan |  nan |     nan |   nan |      nan |            nan | [nan 'CPU URL not valid.Compute URL not valid.' 'CPU URL not valid.'             | ['Same link in both fields' nan] | [4 3 2] |
|    |           |                |                     |                    |                |      |         |       |          |                |  '[Error] Can not compute openCL benchmark' 'Compute URL not valid.'             |                                  |         |
|    |           |                |                     |                    |                |      |         |       |          |                |  '[Error] Can not compute CPU benchmark[Error] Can not compute openCL benchmark' |                                  |         |
|    |           |                |                     |                    |                |      |         |       |          |                |  '[Error] Can not compute CPU benchmark']                                        |                                  |         |

In [15]:
Unique.columns

Index(['team_id', 'machine_name', 'Single core score', 'Multi core score',
       'OpenCL score', 'OS', 'Model', 'CPU', 'Memory', 'Graphic Card',
       'comments', 'observations', 'freq'],
      dtype='object')

Observation: From the above operations, we can see that some of the columns have high number of null anf unique values that will not contribute towards further analysis. So, we can drop them.

## **Dropping Machine name column** ##

In [16]:
pc_details = pc_details.drop(['machine_name'], axis=1)

In [17]:
pc_details.head()

,team_id,Single core score,Multi core score,OpenCL score,OS,Model,CPU,Memory,Graphic Card,comments,observations,freq
0,1001,1142,2148,NaN,Ubuntu 18.04.5 LTS,Dell Inc. Inspiron 3593,Intel Core i3-1005G1,3.62 GB,NaN,NaN,Same link in both fields,4
1,1001,543,1132,3167,Ubuntu 20.04.3 LTS,HP HP Laptop 15q-bu0xx,Intel Core i3-6006U,3.64 GB,Intel(R) HD Graphics 520 (SKL GT2),NaN,NaN,4
2,1001,836,1525,3002,Ubuntu 20.04.3 LTS,HP HP Laptop 14q-bu0xx,Intel Core i5-7200U,3.73 GB,Intel(R) HD Graphics 620 (KBL GT2),NaN,NaN,4
3,1001,601,2281,2946,Ubuntu 20.04.3 LTS,LENOVO 82C7,AMD Ryzen 5 3500U,5.74 GB,AMD RADV RAVEN (ACO),NaN,NaN,4
4,1002,1060,3394,5735,Microsoft Windows 10 Home Single Language (64-...,Dell Inc. G3 3590,Intel Core i7-9750H,2,3.14 GB,NaN,NaN,4

In [18]:
uni_dict1, uni_value1 = unique_chart(pc_details)
Unique1 = pd.DataFrame([uni_dict1, uni_value1]) 
print(Unique1.to_markdown())

|    |   team_id |   Single core score |   Multi core score |   OpenCL score |   OS |   Model |   CPU |   Memory |   Graphic Card | comments                                                                         | observations                     | freq    |
|---:|----------:|--------------------:|-------------------:|---------------:|-----:|--------:|------:|---------:|---------------:|:---------------------------------------------------------------------------------|:---------------------------------|:--------|
|  0 |      1481 |                1154 |               2739 |           3441 |  101 |    1006 |   412 |      134 |            190 | 6                                                                                | 1                                | 3       |
|  1 |       nan |                 nan |                nan |            nan |  nan |     nan |   nan |      nan |            nan | [nan 'CPU URL not valid.Compute URL not valid.' 'CPU URL not valid.'             | ['Same link in both fields' nan] | [4 3 2] |
|    |           |                     |                    |                |      |         |       |          |                |  '[Error] Can not compute openCL benchmark' 'Compute URL not valid.'             |                                  |         |
|    |           |                     |                    |                |      |         |       |          |                |  '[Error] Can not compute CPU benchmark[Error] Can not compute openCL benchmark' |                                  |         |
|    |           |                     |                    |                |      |         |       |          |                |  '[Error] Can not compute CPU benchmark']                                        |                                  |         |

In [19]:
Unique1.columns

Index(['team_id', 'Single core score', 'Multi core score', 'OpenCL score',
       'OS', 'Model', 'CPU', 'Memory', 'Graphic Card', 'comments',
       'observations', 'freq'],
      dtype='object')

## **Removing string data from memory column**

In [20]:
pc_details['Memory'] = pc_details['Memory'].str.replace('GB', ' ')

In [21]:
pc_details.head()

,team_id,Single core score,Multi core score,OpenCL score,OS,Model,CPU,Memory,Graphic Card,comments,observations,freq
0,1001,1142,2148,NaN,Ubuntu 18.04.5 LTS,Dell Inc. Inspiron 3593,Intel Core i3-1005G1,3.62,NaN,NaN,Same link in both fields,4
1,1001,543,1132,3167,Ubuntu 20.04.3 LTS,HP HP Laptop 15q-bu0xx,Intel Core i3-6006U,3.64,Intel(R) HD Graphics 520 (SKL GT2),NaN,NaN,4
2,1001,836,1525,3002,Ubuntu 20.04.3 LTS,HP HP Laptop 14q-bu0xx,Intel Core i5-7200U,3.73,Intel(R) HD Graphics 620 (KBL GT2),NaN,NaN,4
3,1001,601,2281,2946,Ubuntu 20.04.3 LTS,LENOVO 82C7,AMD Ryzen 5 3500U,5.74,AMD RADV RAVEN (ACO),NaN,NaN,4
4,1002,1060,3394,5735,Microsoft Windows 10 Home Single Language (64-...,Dell Inc. G3 3590,Intel Core i7-9750H,2,3.14 GB,NaN,NaN,4

In [22]:
pc_details.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5684 entries, 0 to 5683
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   team_id            5684 non-null   int64
 1   Single core score  5684 non-null   object
 2   Multi core score   5684 non-null   object
 3   OpenCL score       3934 non-null   object
 4   OS                 5684 non-null   object
 5   Model              5684 non-null   object
 6   CPU                5684 non-null   object
 7   Memory             5684 non-null   object
 8   Graphic Card       3934 non-null   object
 9   comments           1366 non-null   object
 10  observations       1750 non-null   object
 11  freq               5684 non-null   int64
dtypes: int64(2), object(10)
memory usage: 577.3+ KB

## **Dropping frequency column**

In [23]:
pc_details = pc_details.drop(['freq'], axis=1)

In [24]:
pc_details.head()

,team_id,Single core score,Multi core score,OpenCL score,OS,Model,CPU,Memory,Graphic Card,comments,observations
0,1001,1142,2148,NaN,Ubuntu 18.04.5 LTS,Dell Inc. Inspiron 3593,Intel Core i3-1005G1,3.62,NaN,NaN,Same link in both fields
1,1001,543,1132,3167,Ubuntu 20.04.3 LTS,HP HP Laptop 15q-bu0xx,Intel Core i3-6006U,3.64,Intel(R) HD Graphics 520 (SKL GT2),NaN,NaN
2,1001,836,1525,3002,Ubuntu 20.04.3 LTS,HP HP Laptop 14q-bu0xx,Intel Core i5-7200U,3.73,Intel(R) HD Graphics 620 (KBL GT2),NaN,NaN
3,1001,601,2281,2946,Ubuntu 20.04.3 LTS,LENOVO 82C7,AMD Ryzen 5 3500U,5.74,AMD RADV RAVEN (ACO),NaN,NaN
4,1002,1060,3394,5735,Microsoft Windows 10 Home Single Language (64-...,Dell Inc. G3 3590,Intel Core i7-9750H,2,3.14 GB,NaN,NaN

In [25]:
pc_details['Graphic Card']

0                                      NaN
1       Intel(R) HD Graphics 520 (SKL GT2)
2       Intel(R) HD Graphics 620 (KBL GT2)
3                     AMD RADV RAVEN (ACO)
4                                  3.14 GB
                       ...
5679                                   NaN
5680                                   NaN
5681                                   NaN
5682                                   NaN
5683                                   NaN
Name: Graphic Card, Length: 5684, dtype: object

##**Analysing null values and unique values, dropping some columns**##

In [26]:
pc_details.isna().sum()

team_id                 0
Single core score       0
Multi core score        0
OpenCL score         1750
OS                      0
Model                   0
CPU                     0
Memory                  0
Graphic Card         1750
comments             4318
observations         3934
dtype: int64

In [27]:
pc_details['comments']

0                                            NaN
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN
                          ...
5679    CPU URL not valid.Compute URL not valid.
5680    CPU URL not valid.Compute URL not valid.
5681    CPU URL not valid.Compute URL not valid.
5682    CPU URL not valid.Compute URL not valid.
5683    CPU URL not valid.Compute URL not valid.
Name: comments, Length: 5684, dtype: object

In [28]:
pc_details['observations']

0       Same link in both fields
1                            NaN
2                            NaN
3                            NaN
4                            NaN
                  ...
5679    Same link in both fields
5680    Same link in both fields
5681    Same link in both fields
5682    Same link in both fields
5683    Same link in both fields
Name: observations, Length: 5684, dtype: object

In [29]:
pc_details = pc_details.drop(['comments', 'observations'], axis=1)

In [30]:
pc_details.head()

,team_id,Single core score,Multi core score,OpenCL score,OS,Model,CPU,Memory,Graphic Card
0,1001,1142,2148,NaN,Ubuntu 18.04.5 LTS,Dell Inc. Inspiron 3593,Intel Core i3-1005G1,3.62,NaN
1,1001,543,1132,3167,Ubuntu 20.04.3 LTS,HP HP Laptop 15q-bu0xx,Intel Core i3-6006U,3.64,Intel(R) HD Graphics 520 (SKL GT2)
2,1001,836,1525,3002,Ubuntu 20.04.3 LTS,HP HP Laptop 14q-bu0xx,Intel Core i5-7200U,3.73,Intel(R) HD Graphics 620 (KBL GT2)
3,1001,601,2281,2946,Ubuntu 20.04.3 LTS,LENOVO 82C7,AMD Ryzen 5 3500U,5.74,AMD RADV RAVEN (ACO)
4,1002,1060,3394,5735,Microsoft Windows 10 Home Single Language (64-...,Dell Inc. G3 3590,Intel Core i7-9750H,2,3.14 GB

In [31]:
a = pc_details['OS'].unique()
print(sorted(a))

['10', '11', '2', '3', '4', '5', '6', '7', '8', '9', 'Android 10', 'Android 11', 'Android 9', 'Arch Linux', 'ArcoLinux', 'Artix Linux', 'Debian GNU/Linux 9 (stretch)', 'Fedora 34 (Workstation Edition)', 'Garuda Linux', 'Kali GNU/Linux Rolling', 'Linux Mint 20.1', 'Linux Mint 20.2', 'Manjaro Linux', 'Manjaro Linux 5.10.59-1-MANJARO x86_64', 'Microsoft Windows 10 Education (64-bit)', 'Microsoft Windows 10 Education N (64-bit)', 'Microsoft Windows 10 Enterprise (64-bit)', 'Microsoft Windows 10 Enterprise 2016 LTSB (64-bit)', 'Microsoft Windows 10 Home (64-bit)', 'Microsoft Windows 10 Home Insider Preview Single Language (64-bit)', 'Microsoft Windows 10 Home Single Language (64-bit)', 'Microsoft Windows 10 Pro (64-bit)', 'Microsoft Windows 10 Pro Education (64-bit)', 'Microsoft Windows 10 Pro N (64-bit)', 'Microsoft Windows 10 Pro for Workstations (64-bit)', 'Microsoft Windows 11 Enterprise (64-bit)', 'Microsoft Windows 11 Home (64-bit)', 'Microsoft Windows 11 Home Insider Preview (64-bit)', 'Microsoft Windows 11 Home Insider Preview Single Language (64-bit)', 'Microsoft Windows 11 Home Single Language (64-bit)', 'Microsoft Windows 11 Pro (64-bit)', 'Microsoft Windows 11 Pro Education (64-bit)', 'Microsoft Windows 11 Pro Insider Preview (64-bit)', 'Microsoft Windows 7 Home Basic (64-bit)', 'Microsoft Windows 7 Professional (64-bit)', 'Microsoft Windows 7 Ultimate (64-bit)', 'Microsoft Windows 8.1 (64-bit)', 'Microsoft Windows 8.1 Enterprise (64-bit)', 'Microsoft Windows 8.1 Enterprise N (64-bit)', 'Microsoft Windows 8.1 Pro (64-bit)', 'Microsoft Windows 8.1 Pro with Media Center (64-bit)', 'Microsoft Windows 8.1 Single Language (64-bit)', 'Microsoft Windows 8.1 Single Language with Bing (64-bit)', 'Nil', 'Pop!_OS 18.04 LTS', 'Pop!_OS 20.04 LTS', 'Pop!_OS 21.04', 'Ubuntu 16.04.6 LTS 4.15.0-88-generic x86_64', 'Ubuntu 18.04.3 LTS', 'Ubuntu 18.04.5 LTS', 'Ubuntu 18.04.5 LTS 5.4.0-80-generic x86_64', 'Ubuntu 18.04.5 LTS 5.4.0-81-generic x86_64', 'Ubuntu 18.04.6 LTS', 'Ubuntu 20.04 LTS', 'Ubuntu 20.04.1 LTS', 'Ubuntu 20.04.1 LTS 5.4.0-48-generic x86_64', 'Ubuntu 20.04.2 LTS', 'Ubuntu 20.04.3 LTS', 'Ubuntu 20.04.3 LTS 5.11.0-34-generic x86_64', 'Ubuntu 21.04', 'Windows 10 Pro (64-bit)', 'Windows 6.2 0000001D8E8FE0AC (64-bit)', 'Windows 6.2 0000001F079EE22C (64-bit)', 'Windows 6.2 000000BE9559E04C (64-bit)', 'iOS 13.3', 'macOS 10.13.2 (Build 17C88)', 'macOS 10.14.6 (Build 18G103)', 'macOS 10.14.6 (Build 18G8022)', 'macOS 10.14.6 (Build 18G9323)', 'macOS 10.14.6 (Build 18G95)', 'macOS 10.15.2 (Build 19C57)', 'macOS 10.15.5 (Build 19F101)', 'macOS 10.15.7 (Build 19H114)', 'macOS 10.15.7 (Build 19H1323)', 'macOS 10.15.7 (Build 19H15)', 'macOS 10.15.7 (Build 19H2)', 'macOS 11.0.1 (Build 20B29)', 'macOS 11.0.1 (Build 20B50)', 'macOS 11.1 (Build 20C69)', 'macOS 11.2 (Build 20D64)', 'macOS 11.2.2 (Build 20D80)', 'macOS 11.2.3 (Build 20D91)', 'macOS 11.3 (Build 20E232)', 'macOS 11.3.1 (Build 20E241)', 'macOS 11.4 (Build 20F71)', 'macOS 11.5 (Build 20G71)', 'macOS 11.5.1 (Build 20G80)', 'macOS 11.5.2 (Build 20G95)', 'macOS 11.6 (Build 20G165)', 'macOS 12.0 (Build 21A5304g)', 'macOS 12.0 (Build 21A5506j)']

In [32]:
a = pc_details['CPU'].unique()
print(sorted(a))

['AMD 3020e', 'AMD A10-4600M', 'AMD A12-9720P', 'AMD A4 Pro-3350B', 'AMD A4-3330MX', 'AMD A4-5000', 'AMD A4-6210', 'AMD A4-9120e', 'AMD A4-9125', 'AMD A6-4400M', 'AMD A6-6310', 'AMD A6-7310', 'AMD A6-7400K', 'AMD A6-9220', 'AMD A6-9225', 'AMD A8-5545M', 'AMD A8-6410', 'AMD A8-6500B', 'AMD A8-7410', 'AMD A9-9400', 'AMD A9-9420', 'AMD A9-9420e', 'AMD A9-9425', 'AMD Athlon Gold 3150U', 'AMD Athlon II X2 240', 'AMD Athlon Silver 3050U', 'AMD E1-6010', 'AMD E1-6015', 'AMD E2-6110', 'AMD E2-9000', 'AMD E2-9000e', 'AMD PRO A10-8700B', 'AMD PRO A4-4350B', 'AMD PRO A6-7350B', 'AMD Phenom II X4 840', 'AMD Ryzen 3 2200U', 'AMD Ryzen 3 3100', 'AMD Ryzen 3 3200G', 'AMD Ryzen 3 3200U', 'AMD Ryzen 3 3250U', 'AMD Ryzen 3 3300U with Radeon Vega Mobile Gfx', 'AMD Ryzen 3 4300U', 'AMD Ryzen 3 5300U', 'AMD Ryzen 5 2400G', 'AMD Ryzen 5 2500U', 'AMD Ryzen 5 2600', 'AMD Ryzen 5 3400G', 'AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx', 'AMD Ryzen 5 3500', 'AMD Ryzen 5 3500U', 'AMD Ryzen 5 3500X', 'AMD Ryzen 5 3550H', 'AMD Ryzen 5 3600', 'AMD Ryzen 5 3600X', 'AMD Ryzen 5 3600XT', 'AMD Ryzen 5 4500U', 'AMD Ryzen 5 4600H', 'AMD Ryzen 5 4600HS', 'AMD Ryzen 5 4600HSS', 'AMD Ryzen 5 5500U', 'AMD Ryzen 5 5600H', 'AMD Ryzen 5 5600U', 'AMD Ryzen 5 5600X', 'AMD Ryzen 5 PRO 3500U', 'AMD Ryzen 7 1700', 'AMD Ryzen 7 2700', 'AMD Ryzen 7 2700X', 'AMD Ryzen 7 3700U', 'AMD Ryzen 7 3700X', 'AMD Ryzen 7 3750H', 'AMD Ryzen 7 3800X', 'AMD Ryzen 7 4700U', 'AMD Ryzen 7 4800H', 'AMD Ryzen 7 4800HS', 'AMD Ryzen 7 5700U', 'AMD Ryzen 7 5800H', 'AMD Ryzen 7 5800HS', 'AMD Ryzen 9 4900H', 'AMD Ryzen 9 4900HS', 'AMD Ryzen 9 5900HS', 'AMD Ryzen 9 5900HX', 'AMD Sempron 145', 'ARM Qualcomm', 'ASUSTeK COMPUTER INC. FA506IH', 'ASUSTeK COMPUTER INC. FA706IU', 'ASUSTeK COMPUTER INC. G512LI', 'ASUSTeK COMPUTER INC. G531GT', 'ASUSTeK COMPUTER INC. G712LU', 'ASUSTeK COMPUTER INC. UX333FA', 'ASUSTeK COMPUTER INC. X409JB', 'ASUSTeK COMPUTER INC. X421EPY', 'ASUSTeK COMPUTER INC. X421IA', 'ASUSTeK COMPUTER INC. X509FB', 'ASUSTeK COMPUTER INC. X513EA', 'ASUSTeK COMPUTER INC. X515DA', 'ASUSTeK COMPUTER INC. Z87-DELUXE/DUAL', 'Acer Aspire A715-75G', 'Acer EA50_HC_CR', 'Apple A9', 'Apple Inc. Mac-66F35F19FE2A0D05 MacBookAir5,1', 'Apple Inc. Mac-827FAC58A8FDFA22 MacBookAir8,1', 'Apple Inc. Mac-937CB26E2E02BB01 MacBookAir7,2', 'Apple Inc. Mac-E7203C0F68AA0004 MacBookPro16,3', 'Apple M1', 'CFL Azalea_FMS', 'CFL Covini_CFS', 'CFL Sienta_CFS', 'CZ Scala_CAS', 'Dell Inc. 031C62', 'Dell Inc. 033HWX', 'Dell Inc. 05JF1T', 'Dell Inc. 05K0D2', 'Dell Inc. 061W4M', 'Dell Inc. 06RM8W', 'Dell Inc. 06WNFC', 'Dell Inc. 08HGD3', 'Dell Inc. 0964XR', 'Dell Inc. 09PY2G', 'Dell Inc. 0C6XG5', 'Dell Inc. 0CPWYR', 'Dell Inc. 0CVMNF', 'Dell Inc. 0D24YP', 'Dell Inc. 0FGN4M', 'Dell Inc. 0FV465', 'Dell Inc. 0J6NY6', 'Dell Inc. 0K08H3', 'Dell Inc. 0K83NX', 'Dell Inc. 0M15G0', 'Dell Inc. 0M78VH', 'Dell Inc. 0MF26F', 'Dell Inc. 0MTYV1', 'Dell Inc. 0N1XH2', 'Dell Inc. 0NV0M7', 'Dell Inc. 0NVF5K', 'Dell Inc. 0V1NDP', 'Dell Inc. 0V3F5M', 'Dell Inc. 0W5NTH', 'Dell Inc. 0WPPM6', 'Dell Inc. 0X9KF3', 'Gigabyte Technology Co., Ltd. B450M S2H', 'HP 81EC', 'HP 81EF', 'HP 8487', 'HP 84A7', 'HP 84AA', 'HP 84D4', 'HP 852E', 'HP 8532', 'HP 8533', 'HP 85E0', 'HP 85FC', 'HP 8656', 'HP 866E', 'HP 86D5', 'HP 86E1', 'HP 8742', 'HP 8786', 'HP 87FD', 'HP 881D', 'HP 881E', 'HP 8850', 'Hewlett-Packard 220D', 'Hewlett-Packard 868A', 'IL Floris_IL', 'Intel Celeron 1007U', 'Intel Celeron 2957U', 'Intel Celeron 3865U', 'Intel Celeron N2820', 'Intel Celeron N3050', 'Intel Celeron N3060', 'Intel Celeron N4000', 'Intel Celeron N4020', 'Intel Core 2 Duo E7400', 'Intel Core 2 Duo E7500', 'Intel Core 2 Duo T5750', 'Intel Core 2 Quad Q6600', 'Intel Core i3-1000NG4', 'Intel Core i3-1005G1', 'Intel Core i3-10100', 'Intel Core i3-10110U', 'Intel Core i3-1115G4', 'Intel Core i3-1125G4', 'Intel Core i3-2120', 'Intel Core i3-2120T', 'Intel Core i3-2130', 'Intel Core i3-2310M', 'Intel Core i3-2328M', 'Intel Core i3-2330M', 'Intel Core i3-2348M', 'Intel Core i3-2350M', 'Intel Core i3-3110M', 'Intel Core i3-3120M', 'Intel Core i3-3210', 'Intel Core i3-3217U', 'Intel Core i3-3220', 'Intel Core i3-3227U', 'Intel Core i3-3240', 'Intel Core i3-330M', 'Intel Core i3-350M', 'Intel Core i3-370M', 'Intel Core i3-380M', 'Intel Core i3-4000M', 'Intel Core i3-4005U', 'Intel Core i3-4010U', 'Intel Core i3-4012Y', 'Intel Core i3-4030U', 'Intel Core i3-4130', 'Intel Core i3-4150', 'Intel Core i3-4160', 'Intel Core i3-4160T', 'Intel Core i3-5005U', 'Intel Core i3-5010U', 'Intel Core i3-5015U', 'Intel Core i3-6006U', 'Intel Core i3-6100', 'Intel Core i3-6100T', 'Intel Core i3-6100U', 'Intel Core i3-7020U', 'Intel Core i3-7100', 'Intel Core i3-7100U', 'Intel Core i3-7130U', 'Intel Core i3-8100', 'Intel Core i3-8130U', 'Intel Core i3-8145U', 'Intel Core i3-9100', 'Intel Core i3-9100F', 'Intel Core i5-10200H', 'Intel Core i5-10210U', 'Intel Core i5-10300H', 'Intel Core i5-1030NG7', 'Intel Core i5-1035G1', 'Intel Core i5-1035G4', 'Intel Core i5-1035G7', 'Intel Core i5-1038NG7', 'Intel Core i5-10400F', 'Intel Core i5-10600K', 'Intel Core i5-11300H', 'Intel Core i5-1135G7', 'Intel Core i5-11400', 'Intel Core i5-2300', 'Intel Core i5-2320', 'Intel Core i5-2400', 'Intel Core i5-2400S', 'Intel Core i5-2410M', 'Intel Core i5-2430M', 'Intel Core i5-2450M', 'Intel Core i5-2520M', 'Intel Core i5-3210M', 'Intel Core i5-3230M', 'Intel Core i5-3317U', 'Intel Core i5-3320M', 'Intel Core i5-3330', 'Intel Core i5-3337U', 'Intel Core i5-3340M', 'Intel Core i5-3380M', 'Intel Core i5-3427U', 'Intel Core i5-3437U', 'Intel Core i5-3450', 'Intel Core i5-4200M', 'Intel Core i5-4200U', 'Intel Core i5-4210M', 'Intel Core i5-4210U', 'Intel Core i5-4260U', 'Intel Core i5-4288U', 'Intel Core i5-4300M', 'Intel Core i5-4300U', 'Intel Core i5-4310M', 'Intel Core i5-4310U', 'Intel Core i5-4430', 'Intel Core i5-4460', 'Intel Core i5-4570', 'Intel Core i5-4670T', 'Intel Core i5-480M', 'Intel Core i5-5200U', 'Intel Core i5-520M', 'Intel Core i5-5250U', 'Intel Core i5-5257U', 'Intel Core i5-5300U', 'Intel Core i5-5350U', 'Intel Core i5-540M', 'Intel Core i5-580M', 'Intel Core i5-6200U', 'Intel Core i5-6300U', 'Intel Core i5-6400', 'Intel Core i5-6402P', 'Intel Core i5-6440HQ', 'Intel Core i5-6500', 'Intel Core i5-6500T', 'Intel Core i5-7200U', 'Intel Core i5-7300HQ', 'Intel Core i5-7300U', 'Intel Core i5-7360U', 'Intel Core i5-7400', 'Intel Core i5-7500', 'Intel Core i5-7600', 'Intel Core i5-8210Y', 'Intel Core i5-8250U', 'Intel Core i5-8257U', 'Intel Core i5-8259U', 'Intel Core i5-8265U', 'Intel Core i5-8265UC', 'Intel Core i5-8279U', 'Intel Core i5-8300H', 'Intel Core i5-8365U', 'Intel Core i5-8400', 'Intel Core i5-8500', 'Intel Core i5-9300H', 'Intel Core i5-9300HF', 'Intel Core i5-9400', 'Intel Core i5-9400F', 'Intel Core i5-9500', 'Intel Core i5-9600K', 'Intel Core i7-10510U', 'Intel Core i7-10610U', 'Intel Core i7-1065G7', 'Intel Core i7-10700', 'Intel Core i7-10710U', 'Intel Core i7-10750H', 'Intel Core i7-10870H', 'Intel Core i7-11370H', 'Intel Core i7-1165G7', 'Intel Core i7-2600', 'Intel Core i7-2670QM', 'Intel Core i7-3610QM', 'Intel Core i7-3612QM', 'Intel Core i7-3632QM', 'Intel Core i7-3667U', 'Intel Core i7-3687U', 'Intel Core i7-3720QM', 'Intel Core i7-3740QM', 'Intel Core i7-4510U', 'Intel Core i7-4600U', 'Intel Core i7-4610M', 'Intel Core i7-4710HQ', 'Intel Core i7-4712HQ', 'Intel Core i7-4720HQ', 'Intel Core i7-4770HQ', 'Intel Core i7-4800MQ', 'Intel Core i7-4870HQ', 'Intel Core i7-5500U', 'Intel Core i7-5600U', 'Intel Core i7-5960X', 'Intel Core i7-6498DU', 'Intel Core i7-6500U', 'Intel Core i7-6600U', 'Intel Core i7-6660U', 'Intel Core i7-6700HQ', 'Intel Core i7-6820HQ', 'Intel Core i7-7500U', 'Intel Core i7-7600U', 'Intel Core i7-7660U', 'Intel Core i7-7700', 'Intel Core i7-7700HQ', 'Intel Core i7-7700K', 'Intel Core i7-7820HK', 'Intel Core i7-8550U', 'Intel Core i7-8565U', 'Intel Core i7-8650U', 'Intel Core i7-8700', 'Intel Core i7-8700K', 'Intel Core i7-8750H', 'Intel Core i7-9700F', 'Intel Core i7-9700K', 'Intel Core i7-9750H', 'Intel Core i7-9750HF', 'Intel Core i9-10850K', 'Intel Core i9-9880H', 'Intel Core i9-9900K', 'Intel Core m3-6Y30', 'Intel Pentium 2020M', 'Intel Pentium 3558U', 'Intel Pentium 3825U', 'Intel Pentium 4405U', 'Intel Pentium A1018', 'Intel Pentium A1020', 'Intel Pentium B940', 'Intel Pentium B950', 'Intel Pentium B960', 'Intel Pentium E5700', 'Intel Pentium G2010', 'Intel Pentium G2020', 'Intel Pentium G2030', 'Intel Pentium G4400', 'Intel Pentium G4560', 'Intel Pentium G620', 'Intel Pentium G630', 'Intel Pentium Gold 4417U', 'Intel Pentium J4205', 'Intel Pentium N3530', 'Intel Pentium N3540', 'Intel Pentium N3700', 'Intel Pentium N3710', 'Intel Pentium N4200', 'Intel Pentium T4500', 'Intel Xeon Platinum 8171M', 'KBL Charmander_KL', 'KBL Freed_KLS', 'LENOVO 20K5A0QWIG', 'LENOVO LNVNB161216', 'LENOVO Nano 5A8', 'LENOVO Toronto 5A2', 'MacBookAir10,1', 'MacBookPro17,1', 'Micro-Star International Co., Ltd. B450M PRO-M2 MAX (MS-7B84)', 'Micro-Star International Co., Ltd. MS-16R4', 'Micro-Star International Co., Ltd. MS-16W1', 'Nil', 'PK Azalea_PKS', 'Qualcomm Qualcomm', 'SR Acer One 14 Z1-471', 'Sony Corporation VAIO', 'TIMI TM1941']

## **Grouping all the data based on team id** ##

In [33]:
pc_details['s']=pc_details.groupby(['team_id']).cumcount()+1
pc_details=pc_details.set_index(['s','team_id']).unstack(0)
pc_details.columns=[f"{x}{y}" for x,y in pc_details.columns]
pc_details=pc_details.reset_index()
pc_details.head()

,team_id,Single core score1,Single core score2,Single core score3,Single core score4,Multi core score1,Multi core score2,Multi core score3,Multi core score4,OpenCL score1,...,CPU3,CPU4,Memory1,Memory2,Memory3,Memory4,Graphic Card1,Graphic Card2,Graphic Card3,Graphic Card4
0,1001,1142,543,836,601,2148,1132,1525,2281,NaN,...,Intel Core i5-7200U,AMD Ryzen 5 3500U,3.62,3.64,3.73,5.74,NaN,Intel(R) HD Graphics 520 (SKL GT2),Intel(R) HD Graphics 620 (KBL GT2),AMD RADV RAVEN (ACO)
1,1002,1060,549,416,590,3394,1834,857,1326,5735,...,Intel Core i3-2350M,Intel Core i5-5200U,2,2,2,1,3.14 GB,2.00 GB,NaN,2.00 GB
2,1003,363,451,488,NaN,779,1154,1116,NaN,908,...,Intel Core i3-3110M,NaN,1,1,2,NaN,1.37 GB,1.56 GB,1.37 GB,NaN
3,1004,809,1182,847,770,2303,6647,2474,1643,8153,...,Intel Core i5-8250U,Intel Core i7-6500U,1,2,1,1,2.00 GB 3.00 GHz,6.00 GB,3.16 GB,2.00 GB
4,1005,686,1003,624,827,3318,3848,3610,4071,NaN,...,AMD Ryzen 5 4600H,Intel Core i7-9750H,15.52,1,1,1,NaN,6.00 GB,4.00 GB,6.00 GB 6.00 GHz

In [34]:
b = pc_details['Memory1'].unique()
print(b)

['3.62  ' '2' '1' '15.52  ' '8.00   LPDDR3 2133 MT/s' '7.56  ' '7.69  '
 '7.60  ' '15.30  ' 'Nil' '5.74  ' '7.77  ' '7.68  ' '7.67  ' '15.51  '
 '3.76  ' '4.00    794 MHz' '8.00  ' '8.00   DDR3 1600 MT/s' '3.86  '
 '16.00  ' '11.58  ' '16.00   DDR4 2400 MT/s' '1.95  '
 '16.00   LPDDR4X 3733 MT/s' '7.62  ' '2.84  ' '7.66  ' '4' '7.55  '
 '3.92   DDR3 SDRAM 1599 MHz' '15.57  ' '7.85  ' '3.30  ' '3.63  '
 '4.00   DDR3 SDRAM 665 MHz' '7.64  ' '15.49  ' '6.75  '
 '8.00   LPDDR4X 3733 MT/s' '15.37  ' '8.00   LPDDR3 933 MHz' '3.74  '
 '3.55  ' '3.77  ' '15.41  ' '15.14  ' '3.73  ' '3.71  ' '7.14  '
 '4.00   DDR3 SDRAM 1599 MHz' '7.86  ' '3.75  ' '7.44  ' '3.69  ' '7.63  '
 '15.39  ' '5.59  ' '4.00  ' '11.49  ' '15.55  ' '7.65  ' '7.51  '
 '4.00    798 MHz' '16.00   EDO RAM' '7.52  ']

In [35]:
pc_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481 entries, 0 to 1480
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   team_id             1481 non-null   int64
 1   Single core score1  1481 non-null   object
 2   Single core score2  1481 non-null   object
 3   Single core score3  1429 non-null   object
 4   Single core score4  1293 non-null   object
 5   Multi core score1   1481 non-null   object
 6   Multi core score2   1481 non-null   object
 7   Multi core score3   1429 non-null   object
 8   Multi core score4   1293 non-null   object
 9   OpenCL score1       1111 non-null   object
 10  OpenCL score2       1023 non-null   object
 11  OpenCL score3       952 non-null    object
 12  OpenCL score4       848 non-null    object
 13  OS1                 1481 non-null   object
 14  OS2                 1481 non-null   object
 15  OS3                 1429 non-null   object
 16  OS4                 1293 non-null   object
 17  Model1              1481 non-null   object
 18  Model2              1481 non-null   object
 19  Model3              1429 non-null   object
 20  Model4              1293 non-null   object
 21  CPU1                1481 non-null   object
 22  CPU2                1481 non-null   object
 23  CPU3                1429 non-null   object
 24  CPU4                1293 non-null   object
 25  Memory1             1481 non-null   object
 26  Memory2             1481 non-null   object
 27  Memory3             1429 non-null   object
 28  Memory4             1293 non-null   object
 29  Graphic Card1       1111 non-null   object
 30  Graphic Card2       1023 non-null   object
 31  Graphic Card3       952 non-null    object
 32  Graphic Card4       848 non-null    object
dtypes: int64(1), object(32)
memory usage: 381.9+ KB

## **Cleaning graphic card details**

In [36]:
pc_details['Graphic Card1'] = pc_details['Graphic Card1'].str.replace('GB', ' ')
pc_details['Graphic Card2'] = pc_details['Graphic Card2'].str.replace('GB', ' ')
pc_details['Graphic Card3'] = pc_details['Graphic Card3'].str.replace('GB', ' ')
pc_details['Graphic Card4'] = pc_details['Graphic Card4'].str.replace('GB', ' ')

In [37]:
pc_details['Graphic Card1'] = pc_details['Graphic Card1'].str.replace('GHz', ' ')
pc_details['Graphic Card2'] = pc_details['Graphic Card2'].str.replace('GHz', ' ')
pc_details['Graphic Card3'] = pc_details['Graphic Card3'].str.replace('GHz', ' ')
pc_details['Graphic Card4'] = pc_details['Graphic Card4'].str.replace('GHz', ' ')

In [38]:
pc_details

,team_id,Single core score1,Single core score2,Single core score3,Single core score4,Multi core score1,Multi core score2,Multi core score3,Multi core score4,OpenCL score1,...,CPU3,CPU4,Memory1,Memory2,Memory3,Memory4,Graphic Card1,Graphic Card2,Graphic Card3,Graphic Card4
0,1001,1142,543,836,601,2148,1132,1525,2281,NaN,...,Intel Core i5-7200U,AMD Ryzen 5 3500U,3.62,3.64,3.73,5.74,NaN,Intel(R) HD Graphics 520 (SKL GT2),Intel(R) HD Graphics 620 (KBL GT2),AMD RADV RAVEN (ACO)
1,1002,1060,549,416,590,3394,1834,857,1326,5735,...,Intel Core i3-2350M,Intel Core i5-5200U,2,2,2,1,3.14,2.00,NaN,2.00
2,1003,363,451,488,NaN,779,1154,1116,NaN,908,...,Intel Core i3-3110M,NaN,1,1,2,NaN,1.37,1.56,1.37,NaN
3,1004,809,1182,847,770,2303,6647,2474,1643,8153,...,Intel Core i5-8250U,Intel Core i7-6500U,1,2,1,1,2.00 3.00,6.00,3.16,2.00
4,1005,686,1003,624,827,3318,3848,3610,4071,NaN,...,AMD Ryzen 5 4600H,Intel Core i7-9750H,15.52,1,1,1,NaN,6.00,4.00,6.00 6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,2964,416,777,1059,622,1101,2845,2893,2040,2143,...,Intel Core i5-10300H,Intel Core i5-8265U,1,8.00 LPDDR3 2133 MT/s,1,1,1.56,1.50,4.00,2.00
1477,2965,664,Nil,587,441,4373,Nil,2513,1053,34544,...,Intel Core i5-10210U,Intel Core i3-5005U,2,1,1,1,4.00,1.55,3.12,1.56
1478,2968,Nil,Nil,Nil,Nil,Nil,Nil,Nil,Nil,NaN,...,Nil,Nil,Nil,Nil,Nil,Nil,NaN,NaN,NaN,NaN
1479,2970,Nil,Nil,Nil,Nil,Nil,Nil,Nil,Nil,NaN,...,Nil,Nil,Nil,Nil,Nil,Nil,NaN,NaN,NaN,NaN
1480,2971,Nil,Nil,Nil,Nil,Nil,Nil,Nil,Nil,NaN,...,Nil,Nil,Nil,Nil,Nil,Nil,NaN,NaN,NaN,NaN

## **Analysing values in graphic card columns**

In [39]:
a = pc_details['Graphic Card1'].unique()
print(a)

[nan '3.14  ' '1.37  ' '2.00   3.00  ' '4.00  ' '3.16  ' '2.00  ' '4.92  '
 '3.11  ' '1.50  ' '1.55  ' 'GeForce GTX 1650' '6.00  ' '6.37  '
 '4.00 MB x 1' '3.12  ' '3.82  ' '3.95  ' '3.15  ' '5.52  '
 'AMD RADV RAVEN (ACO)' '3.00  ' 'AMD RADV POLARIS11 (ACO)' '4.02  '
 '1.56  ' '3.08  ' '1.95   800 MHz' 'Nil' '1.96   2.50  ' '1.57  '
 '1.33  ' '1.00 MB x 1' '4.71  ' '4.04  ' '1.52  ' '3.10  ' '3.13  '
 '1.59  ' '6.36  ' 'AMD Radeon (TM) R5 M430' '3.09  ' '3.06  ' '6.27  '
 '4.03  ' '2.47  ' '1.54  ' 'Intel(R) Iris(R) Plus Graphics' '1.23  '
 'Apple M1' '3.17  ' '2.00   5.00  ' '1.38  ' '1.22  ' '4.76  ' '6.08  '
 '12.4  ' '2.33  ' 'Intel(R) Iris(R) Xe Graphics' '8.00  ' '5.33  '
 '6.07  ' '4.00   6.00  ' '7.04  ' '3.42  ' '5.80  ' '3.00 MB x 1'
 '6.31  ' '1.61  ' '1.62  ' '1.96  ' '1.24  ' '6.00   6.00  ' '3.99  '
 '2.89  ' '3.98  ' '6.34  ' '2.97  ' '6.33  ' '1.96   3.50  '
 '6.00 MB x 1' '6.00   7.00  ' '1.32  ' '1.02  ' '3.04  ' '3.41  '
 '1.39  ' '5.54  ' '3.40  ' '3.02  ' '4.74  ' '3.81  ' '1.53  ' '6.32  '
 '4.00   4.00  ' '3.00   3.50  ' '3.72  ' '8.00   6.00  ' '1.34  '
 '2.36  ' '12.0  ' '7.01  ' 'AMD Radeon(TM) Vega 8 Graphics' '1.94  '
 '1.49  ' 'Intel(R) UHD Graphics 630 (CFL GT2)' '5.93  ' '3.82   4.00  '
 'Intel(R) UHD Graphics 620' '1.51  ' 'Intel(R) HD Graphics 520' '4.77  '
 '4.73  ' '6.35  ' 'Intel(R) HD Graphics 620' '1.00  ' '6.30  ' '6.29  '
 'GeForce MX250' '3.07  ' '6.28  ' 'AMD Radeon(TM) Graphics'
 'Radeon RX 570 Series' '1.35  ' '512 MB']

In [40]:
a=  pc_details['Graphic Card2'].unique()
print(a)

['Intel(R) HD Graphics 520 (SKL GT2)' '2.00  ' '1.56  ' '6.00  ' '1.59  '
 '4.00  ' nan '3.07  ' '1.55  ' '3.16  ' '3.15  ' '3.14  ' '2.00   3.00  '
 '2.36  ' '3.82   6.00  ' '3.12  ' '1.51  ' '4.59  ' '3.11  ' '3.09  '
 '1.96  ' '1.38  ' '1.96   3.00  ' '5.33  ' '6.34  ' '1.00  ' '3.08  '
 '1.71  ' '4.04  ' '3.17  ' 'AMD RADV RAVEN (ACO)' '7.01  '
 '6.00   7.00  ' '4.02  ' '4.76  ' '5.80  ' '3.13  ' '1.50  ' '1.37  '
 '7.79  ' '3.00 MB x 1' '1.54  ' '3.81  ' '4.77  ' '1.53  ' '3.10  '
 '4.03  ' 'NVIDIA GeForce GTX 1650' '1.39  ' '1.57  ' 'Nil' '3.06  '
 '3.40  ' '5.81  ' '2.99  ' '6.32  ' 'NVIDIA GeForce GTX 1650 Ti' '1.24  '
 'GeForce MX110' '3.00  ' '5.98  ' '3.82  ' '1.22  ' '1.74  '
 'AMD Radeon(TM) Vega 8 Graphics' '4.00   6.00  ' '2.95   3.50  ' '1.23  '
 '8.00  ' 'Intel(R) UHD Graphics 620' '1.52  ' '1.34  ' '1.31  '
 'NVIDIA GeForce MX150' 'Intel(R) HD Graphics 5500 (BDW GT2)' '3.02  '
 '1.61  ' '6.00 MB x 1' '6.40  ' '1.32  ' '6.30  ' '2.93  ' '1.46  '
 '6.33  ' '4.00   4.00  ' 'Apple M1' 'Intel(R) HD Graphics 520' '6.35  '
 'AMD Radeon(TM) R4 Graphics' 'Intel(R) HD Graphics 620'
 'Intel(R) HD Graphics 630 (KBL GT2)' '1.33  ' '8.00   7.00  ' '6.31  '
 '3.04  ' '2.97  ' '1.47  ' '6.14  ' '3.95  ' '7.92  ' '4.75  ' '3.41  '
 '6.07  ' '4.68  ' '5.54  ' '1.35  ' '4.00 MB x 1' 'GeForce MX130'
 '8.00 MB x 1' '4.67  ' '7.03  ' '4.69  ' '3.81   6.00  ' '1.48  '
 '10.7  ' 'AMD Radeon(TM) Graphics' 'Apple A9 GPU'
 'NVIDIA GeForce GTX TITAN' '4.57  ' 'Intel(R) UHD Graphics' '6.27  '
 '6.00   6.00  ' 'AMD 15D8:C9']

The values show that there are also graphic card names mentioned in some rows which should be modified.

##**Analysing null  and unique values**##

In [41]:
print(pc_details.isna().sum().sort_values(ascending=False).to_markdown())

|                    |   0 |
|:-------------------|----:|
| Graphic Card4      | 633 |
| OpenCL score4      | 633 |
| OpenCL score3      | 529 |
| Graphic Card3      | 529 |
| Graphic Card2      | 458 |
| OpenCL score2      | 458 |
| Graphic Card1      | 370 |
| OpenCL score1      | 370 |
| Memory4            | 188 |
| CPU4               | 188 |
| Model4             | 188 |
| OS4                | 188 |
| Multi core score4  | 188 |
| Single core score4 | 188 |
| OS3                |  52 |
| Single core score3 |  52 |
| Model3             |  52 |
| Multi core score3  |  52 |
| Memory3            |  52 |
| CPU3               |  52 |
| Memory1            |   0 |
| Single core score2 |   0 |
| Multi core score1  |   0 |
| Memory2            |   0 |
| CPU2               |   0 |
| Multi core score2  |   0 |
| OS1                |   0 |
| CPU1               |   0 |
| Model2             |   0 |
| Model1             |   0 |
| Single core score1 |   0 |
| OS2                |   0 |
| team_id            |   0 |

In [42]:
def unique_chart(Dataset):
  uni_dict = {}
  uni_value ={}
  keys = Dataset.columns
  for i in keys:
    uni_dict[i] = Dataset[i].nunique()
    if Dataset[i].nunique() <= 10:
      uni_value[i] = Dataset[i].unique()
    else:
      uni_value[i] = None
  return (uni_dict, uni_value)

In [43]:
uni_dict, uni_value = unique_chart(pc_details)
Unique = pd.DataFrame([uni_dict, uni_value]) 
print(Unique.to_markdown())

|    |   team_id |   Single core score1 |   Single core score2 |   Single core score3 |   Single core score4 |   Multi core score1 |   Multi core score2 |   Multi core score3 |   Multi core score4 |   OpenCL score1 |   OpenCL score2 |   OpenCL score3 |   OpenCL score4 |   OS1 |   OS2 |   OS3 |   OS4 |   Model1 |   Model2 |   Model3 |   Model4 |   CPU1 |   CPU2 |   CPU3 |   CPU4 |   Memory1 |   Memory2 |   Memory3 |   Memory4 |   Graphic Card1 |   Graphic Card2 |   Graphic Card3 |   Graphic Card4 |
|---:|----------:|---------------------:|---------------------:|---------------------:|---------------------:|--------------------:|--------------------:|--------------------:|--------------------:|----------------:|----------------:|----------------:|----------------:|------:|------:|------:|------:|---------:|---------:|---------:|---------:|-------:|-------:|-------:|-------:|----------:|----------:|----------:|----------:|----------------:|----------------:|----------------:|----------------:|
|  0 |      1481 |                  723 |                  696 |                  676 |                  608 |                1058 |                 984 |                 914 |                 825 |            1073 |             992 |             914 |             813 |    62 |    54 |    53 |    47 |      519 |      476 |      454 |      419 |    232 |    199 |    183 |    180 |        66 |        56 |        54 |        42 |             123 |             122 |             103 |              94 |
|  1 |       nan |                  nan |                  nan |                  nan |                  nan |                 nan |                 nan |                 nan |                 nan |             nan |             nan |             nan |             nan |   nan |   nan |   nan |   nan |      nan |      nan |      nan |      nan |    nan |    nan |    nan |    nan |       nan |       nan |       nan |       nan |             nan |             nan |             nan |             nan |

In [44]:
pc_details.head()

,team_id,Single core score1,Single core score2,Single core score3,Single core score4,Multi core score1,Multi core score2,Multi core score3,Multi core score4,OpenCL score1,...,CPU3,CPU4,Memory1,Memory2,Memory3,Memory4,Graphic Card1,Graphic Card2,Graphic Card3,Graphic Card4
0,1001,1142,543,836,601,2148,1132,1525,2281,NaN,...,Intel Core i5-7200U,AMD Ryzen 5 3500U,3.62,3.64,3.73,5.74,NaN,Intel(R) HD Graphics 520 (SKL GT2),Intel(R) HD Graphics 620 (KBL GT2),AMD RADV RAVEN (ACO)
1,1002,1060,549,416,590,3394,1834,857,1326,5735,...,Intel Core i3-2350M,Intel Core i5-5200U,2,2,2,1,3.14,2.00,NaN,2.00
2,1003,363,451,488,NaN,779,1154,1116,NaN,908,...,Intel Core i3-3110M,NaN,1,1,2,NaN,1.37,1.56,1.37,NaN
3,1004,809,1182,847,770,2303,6647,2474,1643,8153,...,Intel Core i5-8250U,Intel Core i7-6500U,1,2,1,1,2.00 3.00,6.00,3.16,2.00
4,1005,686,1003,624,827,3318,3848,3610,4071,NaN,...,AMD Ryzen 5 4600H,Intel Core i7-9750H,15.52,1,1,1,NaN,6.00,4.00,6.00 6.00

In [45]:
#pc_details.to_csv('Cleaned_pc_specs1.csv',index=True)